version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: youcoderswork-app
        restart: always
        volumes:
            - .:/var/www
    nginx:
        image: nginx:latest
        container_name: youcoderswork-nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx:/etc/nginx/conf.d
    mysql:
        image: mysql:latest
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '${DB_HOST}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - dbdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: '${DB_HOST}'
            PMA_PORT: 3307
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8090:80"
volumes:
    dbdata:
