version: '3'

networks:
    laravel:
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: youcoderswork-app
        restart: always
        environment:
            - RUNNING_IN_DOCKER=true
        volumes:
            - .:/var/www
        networks:
            - laravel
    nginx:
        image: nginx:latest
        container_name: youcoderswork-nginx
        restart: always
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./nginx:/etc/nginx/conf.d
        networks:
            - laravel
    mysql:
        image: mysql:latest
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
            MYSQL_ROO_USER: '${DB_USERNAME:-root}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - youcodeursdata:/var/lib/mysql
        networks:
            - laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: '${DB_DOCKER_HOST:-mysql}'
            PMA_PORT: '${DB_PORT:-3306}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
            PMA_DATABASE: '${DB_DATABASE}'
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8090:80"
        networks:
            - laravel
volumes:
    youcodeursdata:
