version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: youcoderswork-app
        restart: always
        volumes:
            - .:/var/www
    nginx:
        image: nginx:latest
        container_name: youcoderswork-nginx
        restart: always
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./nginx:/etc/nginx/conf.d
    mysql:
        image: mysql:latest
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
            MYSQL_ROO_USER: '${DB_USERNAME:-root}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - youcodeursdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: '%'
            PMA_PORT: '${DB_PORT:-3306}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
            PMA_DATABASE: '${DB_DATABASE}'
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8000:80"
volumes:
    youcodeursdata:
